--- pyproject.toml.orig	2026-04-15 05:56:36 UTC
+++ pyproject.toml
@@ -4,8 +4,7 @@ readme = "README.rst"
 authors = [{name = "MagicStack Inc", email = "hello@magic.io"}]
 requires-python = '>=3.9.0'
 readme = "README.rst"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = {text = "Apache License, Version 2.0"}
 dynamic = ["version"]
 keywords = [
     "database",
